# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fp2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/1/img/workbench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(233, 241, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("QPushButton{font: 24pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(0, 44, 176);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    color: rgb(50, 131, 255);\n"
"}")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("QPushButton{font: 24pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(0, 44, 176);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    color: rgb(50, 131, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("QPushButton{font: 24pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(0, 44, 176);\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255,0,0);\n"
"    color: rgb(50, 131, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("QPushButton{font: 24pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(0, 44, 176);\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255,0,0);\n"
"    color: rgb(50, 131, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("border-image: url(:/1/img/pict1.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/1/pict1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 24pt \"微软雅黑\";\n"
"background-color: rgba(255, 255, 255,155);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("border-image: url(:/1/pict2.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/2/pict2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("border-image: url(:/1/bill5.png);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/3/bill5.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/1/logo1.png"))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255,155);\n"
"padding: 20px;\n"
"")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 2, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setTristate(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 1, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 4, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_5.setCheckable(True)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 1, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_11.setCheckable(True)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 6, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.page_3)
        self.checkBox.setEnabled(False)
        self.checkBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_18.setEnabled(False)
        self.checkBox_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_18.setCheckable(True)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 6, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_3.setCheckable(True)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 5, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_17.setEnabled(False)
        self.checkBox_17.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_17.setCheckable(True)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 5, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 3, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 7, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.checkBox_19 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 5, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_14.setEnabled(False)
        self.checkBox_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_14.setCheckable(True)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 4, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 7, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.checkBox_15 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 4, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_8.setCheckable(True)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 2, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 8, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMouseTracking(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setOpenExternalLinks(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 1, 1, 2)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 9, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 9, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(200, 10, 301, -1)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(60)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 0, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,155);\n"
"\n"
"border: 1px solid #808080;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 237, 232);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255,155);")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 2, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_2)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "票聚合"))
        self.pushButton.setText(_translate("MainWindow", "首页"))
        self.pushButton_2.setText(_translate("MainWindow", "产品介绍"))
        self.pushButton_3.setText(_translate("MainWindow", "识别"))
        self.pushButton_4.setText(_translate("MainWindow", "统计"))
        self.label_2.setText(_translate("MainWindow", "您      的      专      属      数      据      分      析      师"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">近年来，我国经济飞速发展，发票在日常生活中的应用频率快速升高。我国企业录入票据信息多采用会计人员手动的方式，该方式会耗费大量的人力、物力、财力，尤其是当会计人员录入信息的时候，过程需要耗费大量的时间还可能出现差错，无法满足企业对于工作效率的要求。票据识别辅助系统项目可以节约公司的人员开支并且将差错降到最低，大大的减少了工作的时间，以至于大大提高工作效率。票据识别辅助系统可靠性好，实用价值高，拥有广泛的应用前景。针对于传统的发票信息录入模式，会耗费大量的人力、物力、财力，尤其是当会计人员录入信息的时候，过程需要耗费大量的时间还可能出现差错。基于此，我们小组制作了票据识别辅助系统，拟采用深度学习图像识别技术，基于Optical Character Recognition（光学字符识别），采用了较为成熟的Paddle Ocr，实现自动采集发票上的信息，选择性提取需要的信息内容，并输出保存为excel表格。票据识别辅助系统，与传统的人工录入数据相比，可以节约公司的人员开支并且将差错降到最低，大大的减少了工作的时间，以至于大大提高工作效率。</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "选择文件夹"))
        self.pushButton_6.setText(_translate("MainWindow", "选择pdf文件"))
        self.checkBox_9.setText(_translate("MainWindow", "发票代码"))
        self.checkBox_6.setText(_translate("MainWindow", "密码区"))
        self.checkBox_16.setText(_translate("MainWindow", "收款人"))
        self.checkBox_5.setText(_translate("MainWindow", "公司名称"))
        self.checkBox_11.setText(_translate("MainWindow", "纳税人识别号"))
        self.label_9.setText(_translate("MainWindow", "销售方信息："))
        self.checkBox_10.setText(_translate("MainWindow", "机器编号"))
        self.label_7.setText(_translate("MainWindow", "选择信息："))
        self.checkBox_4.setText(_translate("MainWindow", "开户行及账号"))
        self.checkBox_7.setText(_translate("MainWindow", "开票日期"))
        self.checkBox.setText(_translate("MainWindow", "公司地址"))
        self.checkBox_18.setText(_translate("MainWindow", "纳税人识别号"))
        self.checkBox_3.setText(_translate("MainWindow", "公司地址"))
        self.checkBox_17.setText(_translate("MainWindow", "公司电话"))
        self.checkBox_13.setText(_translate("MainWindow", "校验码"))
        self.pushButton_8.setText(_translate("MainWindow", "全部不选"))
        self.checkBox_19.setText(_translate("MainWindow", "复核"))
        self.checkBox_14.setText(_translate("MainWindow", "公司名称"))
        self.checkBox_2.setText(_translate("MainWindow", "开户行及账号"))
        self.pushButton_7.setText(_translate("MainWindow", "全选"))
        self.checkBox_15.setText(_translate("MainWindow", "开票人"))
        self.checkBox_8.setText(_translate("MainWindow", "公司电话"))
        self.checkBox_12.setText(_translate("MainWindow", "发票号码"))
        self.pushButton_9.setText(_translate("MainWindow", "开始识别信息"))
        self.label_8.setText(_translate("MainWindow", "购买方信息："))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://inv-veri.chinatax.gov.cn/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#0000ff;\">检验发票防伪码</span></a></p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "打开图片所在文件夹"))
        self.pushButton_11.setText(_translate("MainWindow", "打开表格所在文件夹"))
        self.pushButton_12.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_13.setText(_translate("MainWindow", "开始统计"))
        self.pushButton_14.setText(_translate("MainWindow", "查看结果文件"))
import ui.tup_rc
